export type TagVariant =
  | "vue"
  | "nuxt"
  | "tailwind"
  | "laravel"
  | "pinia"
  | "gsap"
  | "three"
  | "react"
  | "node"
  | "html"
  | "css"
  | "javascript"
  | "typescript"
  | "bootstrap"
  | "php"
  | "mysql"
  | "vuelidate"
  | "axios"
  | "socketio"
  | "chartjs"
  | "primevue"
  | "zod"
  | "nestjs"
  | "mongodb"
  | "i18n"
  | "pusher"
  | "sass"
  | "nuxtui";

export const tagLabels = {
  vue: "Vue.js",
  nuxt: "Nuxt.js",
  tailwind: "Tailwind CSS",
  laravel: "Laravel",
  pinia: "Pinia",
  gsap: "GSAP",
  three: "Three.js",
  react: "React",
  node: "Node.js",
  html: "HTML",
  css: "CSS",
  javascript: "JavaScript",
  typescript: "TypeScript",
  bootstrap: "Bootstrap",
  php: "PHP",
  mysql: "MySQL",
  vuelidate: "Vuelidate",
  axios: "Axios",
  socketio: "Socket.IO",
  chartjs: "Chart.js",
  primevue: "PrimeVue",
  zod: "Zod",
  nestjs: "NestJS",
  mongodb: "MongoDB",
  i18n: "i18n",
  pusher: "Pusher",
  sass: "SASS",
  nuxtui: "NuxtUI",
} as const satisfies Record<TagVariant, string>;
